/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "motor_command.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MotorInitProto, MotorInitProto, AUTO)


PB_BIND(MotorMoveProto, MotorMoveProto, AUTO)


PB_BIND(MotorConfigProto, MotorConfigProto, AUTO)


PB_BIND(MotorMoveAllProto, MotorMoveAllProto, AUTO)


PB_BIND(MotorTareProto, MotorTareProto, AUTO)


PB_BIND(MotorReportProto, MotorReportProto, AUTO)


PB_BIND(AllMotorReportProto, AllMotorReportProto, AUTO)


PB_BIND(IOReadRequestProto, IOReadRequestProto, AUTO)


PB_BIND(IOReadProto, IOReadProto, AUTO)


PB_BIND(MotorTareIfProto, MotorTareIfProto, AUTO)



